### ISSUE TITLE
Pyfancy v3

### ISSUE THREAD

**Issue by CosmicWebServices** [ilovecode1/pyfancy#51]
I want to start thinking about creating the next version of Pyfancy. Just some things I want to do. Instead of just styling the terminal I now want Pyfancy to work for all things terminal such as progress bars, menus and better inputs. I also want it to be cross-compatible and light weight.

- [ ] Better formatting based on bbcode or markdown.
- [ ] Progress bars
- [ ] Menu select
- [ ] Long console prints with "scroll bars"
- [ ] Plugins?

Also some non-coding things:

- [ ] Better website
- [x] Pip (finally)
- [ ] Better review system
- [ ] Cleaner file system

**Comment by TheMonsterFromTheDeep** [comment]
If it's meant to be supported on as many platforms as possible, we should probably look into using curses.

**Comment by CosmicWebServices** [comment]
@TheMonsterFromTheDeep Hello again! Yes, that was one of the options I was looking at. Have not had tons of time to work on Pyfancy unforchanatly.

**Comment by TheMonsterFromTheDeep** [comment]
@CosmicWebServices I might, just for fun, look into some possibilities this weekend. I imagine that there are also libraries for parsing Markdown/BBCode out there.

**Comment by joker314** [comment]
Ooh, interesting stuff! I might look into some of the scrolling bars and such over the weekend

**Comment by CosmicWebServices** [comment]
@TheMonsterFromTheDeep @joker314 Yay! Cool... I need to set aside time to really start working on this again. Any other ideas for additions?

**Comment by CosmicWebServices** [comment]
@TheMonsterFromTheDeep There are plenty of Markdown parses in python but unfortunately they output as HTML... well at least he ones I have found.

**Comment by joker314** [comment]
Ah, we need something to parse but not convert

**Comment by CosmicWebServices** [comment]
Also I made a v2 branch... unless we want to do what we did before and make a fork

**Comment by CosmicWebServices** [comment]
I am still researching how to parse markdown with python. We could make our own solution if it is better that way

**Comment by joker314** [comment]
I found that making a fork was really unfair on us because we contributed loads of code and barely showed up in the statistics. :(

I think branches are good 👍 

(Ooh, could you make a note in the README not to trust the data in the GitHub stats)

**Comment by CosmicWebServices** [comment]
@joker314 Yeah I can do that and yes that was pretty unfair...

**Comment by CosmicWebServices** [comment]
@joker314 Fixed #56

**Comment by CosmicWebServices** [comment]
Also I think I should update the v2 branch because it is a little behind...

**Comment by jeandrek** [comment]
@joker314 I don't think anybody would really mind, but it's fine.

Edit: Sorry about the double post, my computer powered off and when I started Firefox again it didn't show my message so I assumed I hadn't posted it yet&hellip;

**Comment by Jonathan50** [comment]
@joker314 I don't think anyone would really mind, but it's okay.

**Comment by TheMonsterFromTheDeep** [comment]
It looks like it would be possible to use https://github.com/lepture/mistune for markdown parsing.

**Comment by joker314** [comment]
@TheMonsterFromTheDeep Which bit of it makes you say that?

**Comment by TheMonsterFromTheDeep** [comment]
It lets you plug in a custom renderer class, which simply defines methods for each markdown construct.

It might be a little kludgy when combined with curses, because it is supposed to return a value while here it would be printing a value, but it would probably work.

**Comment by jeandrek** [comment]
Also, the 32 colour codes can be trivially generated from the 8 basic colours (add 30 for foreground colour, 40 for background, 90 for bright foreground, and 100 for bright background).

Could be something like this:
```python
colors = ['black', 'red', 'green', 'yellow', 'blue', 'magenta', 'cyan', 'grey']
for (c, name) in enumerate(colors):
    codes[name] = c+30
    codes[name+'_bg'] = c+40
    codes['light_'+name] = c+90
    codes['light_'+name+'_bg']
```
(This code won't work with the names of the blacks/greys/whites though.)

**Comment by CosmicWebServices** [comment]
@Jonathan50 Cool :D is there any syntax changes we should make? Or does the chaining work for now?

**Comment by TheMonsterFromTheDeep** [comment]
@Jonathan50: the question, of course, is whether we do want to migrate to curses, at which point those codes will not be used at all.

**Comment by CosmicWebServices** [comment]
Pyfancy 3 thumbnail/logo made with [carbon](https://carbon.now.sh/?bg=rgba(255,255,255,1)&t=dracula&l=python&ds=true&wc=true&wa=false&pv=22px&ph=32px&ln=true&code=pyfancy().blue(%223%22).output())

![carbon 2](https://user-images.githubusercontent.com/10731781/36340838-8063d4f6-13b2-11e8-8811-9425ff9538ca.png)

**Comment by CosmicWebServices** [comment]
soooo....

**Comment by CosmicWebServices** [comment]
What should I being doing first that would be helpful?

**Comment by CosmicWebServices** [comment]
@TheMonsterFromTheDeep Just researched curses and it is not very cross compatible... Does not work well with windows so you need to download a port

**Comment by TheMonsterFromTheDeep** [comment]
@CosmicWebServices it's strange that the Python version of curses is that way. It's relatively straightforward to build a Windows application with curses in C simply by using MinGW.

However, there's another reason curses doesn't exactly work: although it gives you control over the whole screen, it doesn't really provide a way to simply color your output. That is, if you were designing a tool such as `ls`, which merely prints output to your console but doesn't actually run an entire command-line user interface, it wouldn't really be possible to use curses.

So I think curses might not be quite the best option.

**Comment by CosmicWebServices** [comment]
@TheMonsterFromTheDeep Gotcha okay so maybe we should start designing what the library looks like now

**Comment by CosmicWebServices** [comment]
I am going to start working on lots of open source projects this summer including this one...

So basically just some questions relating to this project.

Keep the syntax?
How should/can the interactive elements (menus, progress bars, etc) work?
New name?
To curses or not to curses?
etc.

**Comment by TheMonsterFromTheDeep** [comment]
@CosmicWebServices if there's some way to call C api's from Python, it would be pretty easy to get this to work on Windows using the Windows console API.

Curses is, I think, inappropriate for the reasons discussed previously.

**Comment by CosmicWebServices** [comment]
https://docs.python.org/2/extending/extending.html

**Comment by CosmicWebServices** [comment]
Working on an update using this package https://github.com/peterbrittain/asciimatics

**Comment by joker314** [comment]
Hmm, it looks interesting. Why wouldn't people use that library instead of us, though?

**Comment by joker314** [comment]
I suppose our API is much more focused, light-weight, and easier to use for styling text.

**Comment by CosmicWebServices** [comment]
That's what I was thinking of... I may just look through the source code to see how they do all of the things that the library does and simplify it... I love the x, y capabilities of it. Also font sizes and animation. May not use all of it

**Comment by CosmicWebServices** [comment]
Okay red a bunch of code for the asciimatics and made some test code based on it.

This is my proposal:
- Keep pyfancy as simple as possible even with the added functionality
- Use curses with win32 as a backup (https://docs.microsoft.com/en-us/windows/console/writeconsole). Curses only works with unix based systems
- Python 2 and 3 compatibility
- Keyboard input

Here is an example of how Python 3 would work based on my prototype:
```python
pyfancy().open() # or pyfancy.init()
pyfancy().location(x, y).background(red).red("RED").output() # .output() resets pyfancy variables also
pyfancy().location(x, y).effect(reverse).white("REVERSE").output()
pyfancy().end() # Restore to original terminal state
```

Whatcha think?

**Comment by CosmicWebServices** [comment]
References:
https://github.com/peterbrittain/asciimatics/blob/master/asciimatics/screen.py
https://stackoverflow.com/questions/14779486/curses-alternative-for-windows
https://docs.microsoft.com/en-us/windows/console/writeconsole
https://docs.python.org/3/howto/curses.html
https://docs.python.org/2/howto/curses.html

**Comment by joker314** [comment]
Hmm, it looks good. I'd actually prefer it if it was
- still possible to just get a text representation of what you would need to output to the console to get a certain colour
- not need to repeat the mode twice (once with a variable that the user shouldn't have access to?) `.background(red).red`

**Comment by CosmicWebServices** [comment]
One thing I wanted to add is that you should either be able to turn off curses and fall back to normal support or have Pyfancy 2 still available for people who don't want that.

As for your comments I don't really know what you mean by that

**Comment by joker314** [comment]
What I mean is that I want to replace
```python
pyfancy().location(x, y).background(red).red("RED").output()
```

with something like

```python
pyfancy().location(x, y).background("red").text("RED").output()
```

But also, I want to be able to use the console escape sequences (rather than curses) -- as you suggest. So you can get a string as output, that when fed to print will generate the coloured text.

**Comment by CosmicWebServices** [comment]
Gotcha 👍 I will be releasing the code I have so far once I write it into the v3-develop branch

**Comment by CosmicWebServices** [comment]
Here is the code I made so far:
https://gist.github.com/CosmicWebServices/5c95a271847387e03999074466511f34
Current issue that I cannot figure out is why (line 58 for example) I cannot leave out setting the background without throwing an error.

```
Traceback (most recent call last):
                                    File "curses_test.py", line 5, in <module>
                                                                                 class pyfancy:
                 File "curses_test.py", line 59, in pyfancy
                                                              background(self, "black")
       NameError: name 'self' is not defined
```

**Comment by joker314** [comment]
I believe the error is caused by `self` not having a `background_color` property.

If you call `.add()`, it tries to pass this `None` to curses, which makes it unhappy.

The reason your other examples work, is because they call the `background` function. That then runs line 53:

```python
self.background_color = self.codes[color]
```

**Comment by CosmicWebServices** [comment]
Oh wrong error:

```
Traceback (most recent call last):
                                       File "curses_test.py", line 64, in <module>
     pyfancy().location(0,2).add("").output()
                                               File "curses_test.py", line 56, in add
        curses.init_pair(self.ID, curses.COLOR_WHITE, self.background_color)
                                                                            TypeError: an integer is required (got type str)
```

**Comment by joker314** [comment]
Almost certainly the same issue, though..
