### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by skistaddy** [ilovecode1/pyfancy#7]
I got #1 when I ran `import * from pyfancy` inside of `python`:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyfancy.py", line 27, in <module>
    get = idleorcommandline()
   File "pyfancy.py", line 17, in idleorcommandline
    c = a[b - 1]
IndexError: string index out of range
```

**Comment by CosmicWebServices** [comment]
Try the new version we are working on: https://github.com/TheMonsterFromTheDeep/pyfancy or do pyfancy-simple.py
